services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - app-network

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    volumes:
      - ./post-service:/var/www
      - /var/www/vendor
      - /var/www/storage
    ports:
      - "9001:9000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - mysql
    environment:
      RUN_MIGRATION: "true"
    entrypoint: /var/www/docker-entrypoint.sh
    command: php -S 0.0.0.0:9000 -t public

  notif-service:
    build:
      context: ./notif-service
      dockerfile: Dockerfile
    container_name: notif-service
    volumes:
      - ./notif-service:/var/www
      - /var/www/vendor
      - /var/www/storage
    ports:
      - "9002:9000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      RUN_MIGRATION: "true"
    entrypoint: /var/www/docker-entrypoint.sh
    # command: php artisan queue:work rabbitmq --tries=3 --sleep=3
    command: php -S 0.0.0.0:9000 -t public


volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
