version: '3.8'

services:
  # RabbitMQ dengan dashboard
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postrabbit
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # phpMyAdmin untuk cek database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

  # PostService (Lumen API)
  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    volumes:
      - ./post-service:/var/www
    ports:
      - "9001:9000"
    networks:
      - app-network
    depends_on:
      - rabbitmq

  notif-service:
    build:
      context: ./notif-service
      dockerfile: Dockerfile
    container_name: notif-service
    volumes:
      - ./notif-service:/var/www
    ports:
      - "9002:9000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    command: php artisan queue:work --tries=3 --sleep=2
    
volumes:
  mysql_data:
  redis_data:
